name: Packer Build

on:
  push:
    branches:
      - main

jobs:
  integration-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set Database Environment Variable
        run: echo "DATABASE_URL=postgresql+asyncpg://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@localhost:5432/${{ secrets.POSTGRES_DB }}" >> $GITHUB_ENV
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Run Integration Tests
        run: pytest tests/
        env:
          DATABASE_URL: ${{ env.DATABASE_URL }}
          SECRET_KEY: ${{secrets.TEST_EMAIL_SECRET_KEY}} 
          BASE_URL: "demo.atharvawaranashiwar.me"
          AWS_REGION: ${{secrets.AWS_REGION}}
          SNS_TOPIC_ARN: ${{secrets.SNS_TOPIC_ARN}}
          TOKEN_MAX_AGE: 180

      - name: Clean up
        if: always()
        run: echo "Test run complete"

  packer-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up HashiCorp Packer
        uses: hashicorp/setup-packer@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Packer Build Custom AMI
        run: |
          packer init packer/webapp.pkr.hcl
          packer build -var "aws_profile=${{ secrets.AWS_PROFILE }}" \
                       -var 'ami_users=["${{ secrets.AMI_USERS }}"]' \
                       packer/webapp.pkr.hcl
      # Add the step to share the AMI with the DEMO account
      - name: Share AMI with DEMO account
        run: |
          echo "Fetching AMI ID..."
          AMI_ID=$(aws ec2 describe-images --owners self --filters "Name=name,Values=webapp-ami*" --query 'Images[0].ImageId' --output text)
          
          echo "Sharing the AMI with DEMO account..."
          aws ec2 modify-image-attribute --image-id $AMI_ID --launch-permission "Add=[{UserId=${{ secrets.DEMO_ACCOUNT_ID }}}]"

          echo "Fetching snapshot ID..."
          SNAPSHOT_ID=$(aws ec2 describe-images --image-ids $AMI_ID --query 'Images[0].BlockDeviceMappings[0].Ebs.SnapshotId' --output text)

          echo "Sharing the snapshot with DEMO account..."
          aws ec2 modify-snapshot-attribute --snapshot-id $SNAPSHOT_ID --attribute createVolumePermission --operation-type add --user-ids ${{ secrets.DEMO_ACCOUNT_ID }}

        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}