name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set Database Environment Variable
      env:
        DATABASE_URL: sqlite+aiosqlite:///./test.db
      run: echo "Database URL set for testing"

    - name: Run Tests
      run: pytest tests/
      env:
        DATABASE_URL: sqlite+aiosqlite:///./test.db  # Ensure this matches the above

    - name: Always Succeed
      run: echo "Installed"
