name: Packer Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up HashiCorp Packer
        uses: hashicorp/setup-packer@v2

      - name: Run Packer FMT
        run: packer fmt -check .
      
      - name: Init Packer
        run: packer init packer/webapp.pkr.hcl

      - name: Run Packer Validate
        run: |
            packer init packer/webapp.pkr.hcl
            packer validate -var "aws_profile=${{ secrets.AWS_PROFILE }}" \
                       -var 'ami_users=["${{ secrets.AMI_USERS }}"]' \
                       -var "DB_USERNAME=${{ secrets.POSTGRES_USER }}" \
                       -var "DB_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" \
                       -var "DB_HOST=localhost" \
                       -var "DB_PORT=5432" \
                       -var "DB_NAME=${{ secrets.POSTGRES_DB }}" \
                       packer/webapp.pkr.hcl
